services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://user:password@db:5432/orderdb"
      EXCHANGE_API_URL: "https://api.currencyapi.com/v3/latest"
      EXCHANGE_API_KEY: "cur_live_dmm5yxTIlXleNqqswDcoc6pKpLZ5UGk48VysSmdX"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
